codinggita/laundry_buddy

- BACKEND/.gitignore
- BACKEND/config/db.js
- BACKEND/controllers/orderController.js
- BACKEND/models/userOrder.js
- BACKEND/package-lock.json
- BACKEND/package.json
- BACKEND/routes/orderRoutes.js
- BACKEND/server.js
This pull request introduces the initial folder structure for the backend using the MVC (Model-View-Controller) design pattern. It organizes the backend code into the following directories:
**models**: Contains the schema and data structure for the application.
**controllers**: Manages the business logic and interacts with models and views.
This setup aims to provide a clean and scalable structure for future development.
> Setup Backend Folder Structure with MVC Pattern

- BACKEND/controllers/userController.js
- BACKEND/models/user.js
- BACKEND/routes/userRoute.js
This pull request implements both the user registration and login functionality for the laundry app. It includes:
- User Registration API: Allows new users to register by providing necessary details such as name, email, phone number, building name, room number, and password. The API performs basic validation to ensure all fields are filled and that passwords match before saving the new user to the database.
- User Login API: Authenticates users by validating their email and password. If the credentials match, the user is logged in, and a response is sent confirming the successful login.
- User Model: Defines the schema for the user with fields like name, email, phone number, building name, room number, and password. The email and phone number are set to be unique to prevent duplication.
> Add User Registration and Login APIs

- BACKEND/controllers/user/Authentification/userController.js
- BACKEND/controllers/user/Complaint Form/complaintformController.js
- BACKEND/controllers/user/Order Management/orderController.js
- BACKEND/models/user/Complaint Form/complaintModel.js
- BACKEND/routes/userRoutes/complaintRoutes/complaintRoutes.js
- BACKEND/routes/userRoutes/orderRoutes.js
- BACKEND/routes/userRoutes/userRoute.js
This PR includes various updates and improvements. Since I lost track of individual changes, I am pushing all pending modifications together. Key changes may include bug fixes, feature enhancements, and refactoring.
>  🚀 Miscellaneous Updates: Bug Fixes & Enhancements

- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/Component/Roleselector/Roleselector.jsx
- Frontend/src/Component/User/Login.jsx
- Added navigation functionality to redirect workers to the login page.
- Implemented a setTimeout to navigate users to the dashboard after successful registration.
- Installed lucide-react for improved icon usage in the application.
> Link Worker to Login Page

- Frontend/src/Component/User/Card.jsx
- Frontend/src/Component/User/Dashboard.jsx
- 🚀 This PR adds the User Dashboard UI with dynamic card data, including route, icon, color, and description for different sections (Submit Order, Order History, Daily Rush, Profile). 
- 💡 Additionally, the current date is displayed in a formatted style
- 📸 Screenshot of the dashboard UI is attached for reference."
-
> User Dashboard UI ✨

- Frontend/src/App.jsx
- Frontend/src/Component/User/Dashboard.jsx
- Frontend/src/Component/User/ForgotPassword.jsx
- Frontend/src/Component/User/Sidebar.jsx
This PR includes multiple enhancements for the user dashboard, focusing on responsiveness and navigation improvements:
- Made dashboard header responsive for better viewing on mobile and various screen sizes.
- Updated the forgot password page to be fully responsive.
- Improved routing by updating the user dashboard route structure.
- Added NavLink-based navigation in the sidebar for better user experience.
- Updated styles to support mobile-friendly layouts.
- Enhanced navigation with NavLink for better state management.
- Improved UI consistency across all pages.
- Make dashboard header responsive for mobile and different screen sizes.
- Make the forgot password page responsive.
- Update the user dashboard route.
- Add NavLink navigation to sidebar for user dashboard.
> 🛠️ Improve User Dashboard Responsiveness & Navigation

- Frontend/src/App.jsx
- Frontend/src/Component/User/OrderHistory/Orderhistory.jsx
- Frontend/tailwind.config.js
<html>
<body>
<html><head></head><body><h1>📜 Implement Order History Page with Responsive UI &amp; Sidebar</h1>
<h2>🎯 Overview</h2>
<p>This PR introduces the <strong>Order History Page</strong> with a fully responsive design 📱, an improved UI 🎨, and seamless integration with the sidebar navigation 🧭.</p>
<h2>✨ Changes Implemented</h2>
<ul>
<li>✅ Designed and implemented the <strong>Order History Page</strong>.</li>
<li>📱 Made the page <strong>mobile-friendly</strong> and <strong>responsive</strong> for all screen sizes.</li>
<li>🎨 Improved UI with better spacing, typography, and color contrast.</li>
<li>🏗️ Added route for <strong>User Order History</strong> navigation.</li>
<li>🎨 Applied <strong>custom background colors</strong> for a cleaner look.</li>
</ul>
<h2>📸 Screenshots</h2>
📍 …
>  📜 Implement Responsive Order History Page with Sidebar Integration

- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/App.jsx
- Frontend/src/Component/User/Dashboard.jsx
- Frontend/src/Component/User/Login.jsx
- Frontend/src/Component/User/OrderHistory/Orderhistory.jsx
- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
- Frontend/src/assets/loader/loader.jsx
- Frontend/tailwind.config.js
- Implemented the **Submit Order Form** with fields like Bag Number, Name, Room Number, Building, Number of Items, and Weight.
- Added stepper navigation for the order process.
- Styled the form using Tailwind CSS for a clean and responsive UI.
- Updated the **routes** to integrate the new form seamlessly.
- 🚀 User-friendly and structured form for submitting laundry orders.
- 🎨 Improved UI/UX with proper input fields and icons.
- 🔄 Navigation flow for order submission process.
1. Navigate to the **Submit Order** page.
2. Fill in the required details.
3. Click on the **Continue** button.
4. Ensure that the navigation and form functionalities work as expected.
---
💡 **Review & Feedback Welcome!**
> 🚀 Add Submit Order Form & Update Routes

- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
This PR adds:
- **Step 2:** Weight & Items Page ⚖️👕
- **Step 3:** Payment Review & Screenshot Upload 🏦📸
- Implemented the UI for the Weight & Items selection page.
- Added form fields for entering item weights.
- Integrated a **screenshot upload** option for proof of payment in Step 3.
- Improved responsiveness across different screen sizes.
1. Navigate to the Submit Order page.
2. Fill in order details and proceed to **Step 2**.
3. Enter weights for items and move to **Step 3**.
4. Upload a screenshot and review the payment.
- Let me know if any changes are needed! 😊
---
@mayur2410-tech 🚀
> ✨ Add Weight & Items Page UI & Step 3 with Payment Review 🛍️💳📸

- Frontend/src/App.jsx
- Frontend/src/Component/User/OrderHistory/Orderhistory.jsx
- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
- Added a new route for the user profile.
- The route enables users to view and update their profile details.
- Fixed styling issues across the project.
- Changed the input type to `number` for the relevant input fields.
- Ensures users input only numeric values, improving form validation and UX.
> 🚀 Add User Profile Route, 🛠️ Fix CSS, and 🔢 Update Input Type

- Frontend/src/App.jsx
- Frontend/src/Component/User/Profile/Profile.jsx
This PR adds the **Profile Settings** page where users can manage their personal information and security settings.
- **👤 Personal Information:** Display and update personal details like phone number, room number, bag number, and building.
- **🔐 Security Settings:** Update current and new passwords to enhance account security.
- **✏️ Input Fields:** Added input fields with proper validation for each section to make data entry smooth and error-free.
> 
- Responsive design with a clean and user-friendly layout.
- Icons added to each input field for better UX.
- Styling improvements for better readability.
> 👤 Implement Profile Settings Page with 📝 Personal Info, 🔐 Security, and ✏️ Input Fields

- BACKEND/controllers/user/Authentification/userController.js
- BACKEND/controllers/user/OrderManagement/orderController.js
- BACKEND/middleware/authMiddleware.js
- BACKEND/package-lock.json
- BACKEND/package.json
- BACKEND/routes/userRoutes/orderRoutes.js
This PR adds JWT authentication to secure routes and verify users before processing their requests.  
- 🛡️ **Added JWT authentication middleware** to verify and protect routes.  
- 🔑 **Implemented login functionality** for both Users & Workers using JWT.  
- 🔍 **Extracted userId from authenticated user** in request body for order submissions.  
- 📦 **Installed JWT package** and configured token handling.  
- 🚀 **Protected the `/submit-order` route** by integrating authentication middleware.  
1. Register/Login a user or worker.  
2. Try accessing a protected route with and without a valid token.  
3. Verify token-based authentication flow.  
- Ensure `.env` has `JWT_SECRET` configured.  
- Token expires in **1 hour**, modify if needed.  
🔄 **Ready for review!** 🚀
> 🚀 Implemented JWT Authentication & Middleware Protection

- BACKEND/controllers/user/OrderManagement/orderController.js
- BACKEND/models/userOrder.js
- Updated order submission to fetch user details from the database.
- Removed unnecessary input fields from the request body.
- Ensured security by using authenticated user data.
- Tested API to confirm correct order submission.
- Removed `name`, `buildingName`, `roomNumber`, and `bagNumber` fields.
- Ensured `userId` is used to fetch user details instead.
- Modified schema to accept only `weight` & `numberOfClothes`.
1. Submit an order via the API with authentication.
2. Verify the order details are stored correctly.
3. Ensure the removed fields are no longer required in the request body.
- ✅Code is tested and working as expected.
- ✅ No breaking changes introduced.
> 🔄 Refactored Order Submission: Fetched User Details & Optimized Schema

- BACKEND/controllers/user/Profile-Management/profileController.js
- BACKEND/routes/userRoutes/Profile/userDetails.js
- BACKEND/server.js
- Implemented an API endpoint to fetch user details securely using JWT authentication.  
- Extracted `userId` from the authentication middleware to ensure only authorized users can access their profile.  
- Handled errors for cases like unauthorized access and non-existent users.  
- Successfully tested the API response in Postman.  
- **Created Profile Fetch API** to retrieve user details based on authentication.  
- **Integrated JWT Middleware** to extract user ID securely.  
- **Implemented Error Handling** for unauthorized requests and missing user records.  
- **Tested API in Postman** to ensure proper response and security.  
_If applicable, link related issues here._
> 🆔 Added Secure User Profile Fetch API

- BACKEND/controllers/user/OrderManagement/orderController.js
- BACKEND/routes/userRoutes/orderRoutes.js
- Implemented an API endpoint to fetch a user's order history.  
- Retrieves all orders placed by the authenticated user.  
- Returns total orders along with counts of pending and completed orders.  
- Created `getOrderSummary` function to fetch and format order history.  
- Used authentication middleware to ensure only logged-in users access their data.  
- Sorted orders by `createdAt` in descending order for latest-first display.  
- Extracted user ID from token to securely fetch user-specific orders.  
- Formatted response to include order count, status-wise breakdown, and timestamp.  
1. Make a `GET` request to `/order-history` with a valid token in the Authorization header.  
2. Verify that the response contains order details and counts for pending/completed orders.  
3. Check that …
> 📜 Added User Order History API to Fetch Orders and Summary

- BACKEND/controllers/user/Authentification/userController.js
- BACKEND/models/user.js
- Frontend/src/Component/User/Registration.jsx
This PR introduces a new field, **Bag Number**, to the user registration form and updates the backend to handle it properly. The changes ensure that users can input their bag number during registration, which will be stored in the database.
- 📝 **Frontend:** Added a new input field for **Bag Number** in the registration form.
- 🔗 **Backend:** Modified the database schema and API endpoints to accept and store **Bag Number**.
- 🎨 **UI Enhancements:** Ensured the new field follows the existing form styling for consistency.
1. Navigate to the **registration page**.
2. Fill in all the required fields, including the **Bag Number**.
3. Submit the form and verify that the data is saved correctly in the database.
4. Check the backend logs or database records to confirm the **Bag Number** is …
> 🛍️ Add Bag Number Field to Registration Form & Backend 🛠️

- BACKEND/controllers/user/OrderManagement/orderController.js
- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
- Frontend/src/assets/loader/loader.jsx
- ✅ **Error Handling:** Improved error handling during order submission to provide better feedback.  
- 🔄 **Loader Integration:** Added a loading indicator to enhance user experience while submitting orders.  
- 🔗 **Navigation Update:** After successful order submission, users are now redirected to the success page.  
- Implemented proper error handling to display relevant messages on failure.  
- Centered the loader UI and adjusted background color for better visibility.  
- Added `useNavigate()` to redirect users to the success page after submitting the order.  
- Updated API call logic to include the total number of orders.  
https://github.com/user-attachments/assets/3511d7dc-29b3-430b-bdc7-6f68f1e1f8c3
1. Fill in the order details and click **Submit Order**.  
2. If there's an error, …
> 🛠️ Enhance Order Submission: Error Handling, Loader UI, and Success Page Navigation 🚀

- Frontend/src/App.jsx
- Frontend/src/Component/User/SubmitOrder/OrderConfirmation.jsx
This PR introduces the **Order Confirmation Page** and adds the necessary route for navigation. The page provides users with a confirmation message after successfully placing an order.  
- 📌 Added a new **OrderConfirmation** page component.  
- 🛠️ Updated the routing to include **`/order-confirmation`**.  
- 🎨 Styled the confirmation page for a better user experience.  
1. **Place an order** through the application.  
2. After submission, the app should **navigate to the Order Confirmation Page**.  
3. Verify that all **order details and success messages** are displayed correctly.  
- Further enhancements can be made to **improve UI/UX**.  
- Future scope includes **adding animations or a redirect timer**.  
🔗 **Ready for review!** ✅
> Add Order Confirmation Page and Route 🚀

- Frontend/src/Component/User/SubmitOrder/OrderConfirmation.jsx
- Frontend/src/Component/User/SubmitOrder/OrderContext.jsx
- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
- Frontend/src/main.jsx
This PR refactors the order submission and confirmation flow by implementing **Context API** to manage and share order details (`weight`, `numberOfItems`, and `bagNumber`) between components.  
✅ **Added `OrderContext.jsx`** for global state management.  
✅ **Updated `SubmitOrder.jsx`** to store order details in context instead of local state.  
✅ **Updated `OrderConfirmation.jsx`** to fetch order details from context instead of using props.  
1. Navigate to the order submission page.  
2. Enter the required details (`weight`, `number of items`).  
3. Submit the order and ensure it redirects to the order confirmation page.  
4. Verify that order details (including `bagNumber` fetched from API) are displayed correctly.  
📌 This refactor removes unnecessary prop drilling and improves state …
> 🔄 Implement Context API for Order Data Sharing

- Frontend/src/Component/User/Daily-Rush/Dailyrush.jsx
This PR introduces a new component named `Dailyrush` that displays a "Temporarily Unavailable" message to users. The component includes the following features:
- 🧭 **Sidebar Component**: For consistent navigation across the application.
- 📝 **Main Content**: A centered message informing users that the page is temporarily unavailable.
- 🔙 **Navigation Button**: A button that navigates users back to the user dashboard.
1. 🆕 Added the `Dailyrush` component to display the "Temporarily Unavailable" message.
2. 🧩 Implemented a `Sidebar` component for consistent navigation.
3. 🎨 Styled the content to be centered and visually appealing.
4. 🖱️ Added a button with a link to navigate back to the user dashboard.
1. 🧭 Navigate to the `Dailyrush` page in the application.
2. ✅ Verify that the …
> Add "Temporarily Unavailable" Page to Dailyrush Component 🚫🔄

- Frontend/src/Component/User/OrderHistory/Orderhistory.jsx
This PR adds functionality to fetch and display the order history for users. The key features include:
- **Fetching Order History**: Retrieve the user's past laundry orders from the server using Axios.
- **Loading State**: Implemented a loading state with a `LoaderM` component to enhance the user experience while data is being fetched.
- **Order Details Display**: Display detailed information about each order, including:
- Bag Number
- Room Number
- Number of Items
- Weight
- Status
- Creation Date
1. Fetched order history from the server using Axios.
2. Implemented a loading state with the `LoaderM` component to indicate data fetching.
3. Displayed order details including bag number, room number, number of items, weight, status, and creation date.
4. Integrated the `Sidebar` component …
> 📦📅 Fetch and Display Order History with Enhanced User Experience 

- BACKEND/controllers/user/Profile-Management/profileController.js
- BACKEND/models/user.js
- BACKEND/routes/userRoutes/Profile/userDetails.js
This PR enhances the user profile management functionality by adding an update endpoint, a corresponding route, and a default value for the address field. The key improvements include:
- **Update Endpoint**: Implemented an endpoint to update user profile details, such as phone number, room number, bag number, building name, and address.
- **Validation**: Added validation to check if the phone number is already in use to prevent duplicates.
- **Error Handling**: Included comprehensive error handling for cases where the user is not found or the phone number is already in use.
- **Success Responses**: Provided appropriate success responses upon successful updates.
1. **User Profile Update Endpoint**:
- Added functionality to update user profile details.
- Included validation to check if the …
>  🚀👤 Enhance User Profile Management with Update Endpoint, Route, and Default Address Value

- Frontend/src/App.jsx
- Frontend/src/Component/User/Profile/Profile.jsx
- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
This PR introduces functionality to fetch and display user details in the Profile component. The main focus is to enhance the user experience by allowing users to view and manage their profile information. The key features include:
- **Fetching User Details**: Retrieve user profile details from the server using Axios.
- **Displaying User Information**: Show user details such as name, email, phone number, room number, bag number, building name, and address in the Profile component.
- **Editing Profile Information**: Allow users to edit their profile details directly from the Profile component.
1. **User Details Fetching**:
- Implemented functionality to fetch user profile details from the server.
- Stored fetched user details in the component state and utilized them in the form fields.
2. …
> 🧑‍💼📄 Fetch and Display User Details in Profile Component 

- README.md
This PR adds a detailed `README.md` for the Laundry Management System, covering:  
- 📌 **Project Overview** & Problem Statement  
- ✅ **Solution & Key Features**  
- 🛠 **Tech Stack (Frontend, Backend, Deployment)**  
- 📊 **Success Metrics & Future Enhancements**  
- Provides **clear documentation** for new contributors.  
- Outlines the **project's purpose & structure**.  
- Makes it easy to understand **features & tech choices**.  
✅ Ready for review! Let me know if any changes are needed. 🚀
> 📝 Added Project README with Features, Tech Stack 

- BACKEND/controllers/user/OrderManagement/orderController.js
- Frontend/src/Component/User/Registration.jsx
This pull request addresses the following changes:
- 🛠️ **Fix Order Count:** Resolved the issue with the count of complete orders and pending orders.
- 📱 **Update Mobile Number Input Type:** Corrected the input type of the mobile number to ensure proper formatting and validation.
- 🔄 Fixed the logic for counting complete and pending orders to display accurate numbers.
- 📝 Updated the input type for the mobile number field to ensure it accepts valid phone numbers.
1. **Setup:**
- Ensure the latest code is pulled and dependencies are installed.
2. **Testing Order Count Fix:**
- Navigate to the order management section.
- Verify that the counts for complete and pending orders are accurate.
3. **Testing Mobile Number Input:**
- Navigate to the profile settings or any relevant section with the …
> 🔧📱 Fix Order Count and Update Mobile Number Input Type 

- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
This pull request introduces a change to add labels in the submit form without altering the original UI layout. The addition of labels improves form accessibility and user experience.
- 📝 Added labels to each input field in the submit form to provide clear identification and improve accessibility.
> ✨ Add Label in Submit Form

- Frontend/src/App.jsx
- Frontend/src/Component/User/ForgotPassword.jsx
- Frontend/src/Component/User/Login.jsx
- Frontend/src/Component/User/Profile/Profile.jsx
This pull request introduces the following changes to the authentication flow:
1. **Change Page Title**
- Updated the page title from "Reset Password" to "Forgot Password" for clarity and consistency.
2. **Route Adjustments**
- Edited the route for the "Forgot Password" page to ensure proper navigation and accessibility.
- Updated the Login page route to include a link to the "Forgot Password" page for users who need to reset their password.
3. **UI Enhancements**
- Added a "Forgot Password" button on the Profile page, which directs users to the new "Forgot Password" page route.
- `edit routes`
- Changed the title of the password reset page.
- Adjusted routing paths to reflect the new "Forgot Password" page.
- `edit Login page`
- Included a button for navigating to the "Forgot Password" …
> 🔐 Implement "Forgot Password" Feature and Route Adjustments 🔄

- BACKEND/controllers/user/Authentification/userController.js
- BACKEND/models/user.js
- BACKEND/package-lock.json
- BACKEND/package.json
- BACKEND/routes/userRoutes/userRoute.js
This PR introduces the forgot password functionality, allowing users to reset their password using a secure token sent via email. It includes the following changes:  
- 🛠️ **Added** `resetPasswordToken` and `resetPasswordExpires` fields in the user schema to store the reset token and its expiration time.  
- 📩 **Installed** **Nodemailer** to handle email functionality for sending password reset links.  
- 🔑 **Implemented** `forgotPassword` controller to:  
- 🏷️ Generate a **JWT-based reset token**.  
- 💾 Store the token and expiration time in the database.  
- ✉️ Send an **email with a password reset link**.  
- 🚀 **Created** a new route `/forgot-password` to handle password reset requests.  
1. 📝 **User submits** a password reset request with their registered email.  
2. 🔍 **If the email …
> ✉️ Implement Forgot Password Functionality with JWT & Email Reset

- BACKEND/controllers/user/Authentification/userController.js
- Frontend/src/App.jsx
- Frontend/src/Component/User/ResetPassword.jsx
- 🎨 **Added UI for Reset Password Page** to enhance user experience.  
- 🛤️ **Implemented route for Reset Password** to handle password reset requests.  
- 🔗 **Updated Reset Password link** for proper redirection and functionality.  
1. Users requesting a password reset will be directed to the new **Reset Password Page**.  
2. The route ensures smooth navigation and secure handling of reset requests.  
3. The reset link has been adjusted to improve accuracy and usability.  
- UI tested for responsiveness and usability.  
- Route verified for correct navigation and API request handling.  
- Reset link functionality validated.  
🚀 This update enhances password recovery and improves user accessibility.
> 🚀 Add Reset Password Page UI & Route Implementation 🔐

- BACKEND/controllers/user/Authentification/userController.js
- BACKEND/routes/userRoutes/userRoute.js
---
This pull request introduces the implementation of the reset password functionality and adds the corresponding route to handle password reset requests.
- **🔐 Implement reset password functionality:**
- Validate that the new password and confirm password fields match.
- Verify the token provided in the request parameters.
- Check the validity and expiration of the token.
- Update the user password using bcrypt for secure hashing.
- Clear the reset token and expiration fields after a successful password update.
- Handle errors and send appropriate responses.
- **📬 Add reset password route:**
- Define a POST route for `/reset-password/:token`.
- Integrate the `resetPassword` controller function to handle password reset logic.
- Manual testing was performed to ensure that the password …
> 🔒 Implement Reset Password Functionality and Add Corresponding Route 🚀

- BACKEND/controllers/user/Authentification/userController.js
- Frontend/src/Component/User/ResetPassword.jsx
- Integrated the reset password API with the frontend.  
- Implemented validation to prevent users from reusing their old passwords.  
- Enhanced security measures for password reset functionality.  
- Users can now reset their passwords through the frontend.  
- The system checks if the new password is the same as the old one and prompts the user to choose a different password.  
- **Add the reusing the same password prevention logic**  
- **Integrate reset password API with frontend**  
- Improved security by ensuring users set a fresh password upon reset.  
- Enhanced user experience by providing meaningful feedback on password updates.
> 🔄 Integrate Reset Password API & Prevent Reusing Old Password

- BACKEND/controllers/user/Authentification/userController.js
- BACKEND/routes/userRoutes/Profile/userDetails.js
- Added backend API to update the password with current password verification.
- Prevented users from reusing the same password.
- Integrated the frontend password update form with JWT authentication.
- Displayed success and error messages accordingly for better user experience.
- Created a secure password update route in the backend.
- Implemented validation to ensure the new password is different from the old password.
- Connected the frontend form to the API for seamless password updates.
1. User enters their current password and a new password.
2. System verifies the current password before updating.
3. If the new password matches the old password, an error is displayed.
4. On successful update, a confirmation message is shown.
🚀 This update enhances account security and improves the …
> 🔒 Implement Password Update in Profile with Security Enhancements

- BACKEND/routes/userRoutes/Profile/userDetails.js
- Frontend/src/Component/User/Profile/Profile.jsx
- Implemented backend API to update the password with current password verification.  
- Prevented users from reusing the same password.  
- Integrated the frontend form with JWT authentication.  
- Displayed success/error messages accordingly for better user experience.  
- Added the route for updating the password.  
✅ Enhances security & improves user experience! 🔐✨
> 🚀 Integrate Update Password API with Frontend 🔗🔒

- Frontend/src/Component/User/Sidebar.jsx
- Closes the sidebar when the user logs out  
- Displays a toast notification for successful logout  
- Removes authentication token from local storage  
- Redirects to the login page after 2 seconds  
- Updated the `logout` function to handle sidebar state  
- Fixed the toast notification issue  
- Ensured smooth user experience with a delay before redirection  
🚀 Enhancing user experience by improving logout flow!
> 🔒 Implement Logout Functionality  🚀

- Frontend/src/App.jsx
- Frontend/src/Component/User/Complaint-Form/ComplaintForm.jsx
- Designed and implemented the UI for the complaint form.  
- Added a new route to navigate to the complaint form.  
- Ensured a user-friendly experience with a structured form layout.  
- Applied necessary styles for better visibility and usability.  
- Improved accessibility and responsiveness.  
- Ensured smooth navigation and integration with the existing system.  
- Verified UI rendering correctly across different devices.  
- Ensured route navigation functions as expected.  
🎯 **Users can now easily submit complaints through the newly added form!**
> 📝 Add Complaint Form UI & Route Integration 🚀

- Frontend/src/Component/User/Dashboard.jsx
- Frontend/src/Component/User/ForgotPassword.jsx
- Frontend/src/Component/User/Login.jsx
- Frontend/src/Component/User/OrderHistory/Orderhistory.jsx
- Frontend/src/Component/User/Profile/Profile.jsx
- Frontend/src/Component/User/Registration.jsx
- Frontend/src/Component/User/ResetPassword.jsx
- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
This update replaces the local backend URLs in the frontend with the deployed backend URLs. Now, all API requests will be directed to the live backend, ensuring the application works seamlessly in the production environment.  
✅ Replaced local backend URLs with deployed URLs across multiple components.  
✅ Updated API endpoints in:  
- 🔑 Authentication (Login, Registration, Forgot Password, Reset Password)  
- 📊 User Dashboard  
- 📜 Order History  
- 🧑‍💼 Profile Management  
- 📦 Submit Order  
⚡ Prepares the frontend for deployment by linking it to the live backend.  
⚡ Ensures smooth communication between the frontend and backend in a production setup.  
⚡ Prevents API request failures due to incorrect URLs.
> 🔗 Update Backend URLs in Frontend with Deployed URLs 🚀

- Frontend/src/Component/User/Profile/Profile.jsx
- Frontend/vite.config.js
This pull request removes the redundant toast container from the codebase to streamline the user interface and improve maintainability. 💻✨
- Removed the unnecessary toast container component 🗑️
- Updated references and documentation accordingly 📚
The removal of the redundant toast container simplifies the code and enhances the user interface by eliminating unnecessary elements. This change contributes to a cleaner and more maintainable codebase. 🌿🧹
---
Please review the changes and provide feedback. Thank you! 🙌
> Remove redundant toast container 🗑️ for cleaner UI✨

- BACKEND/controllers/user/Authentification/userController.js
- BACKEND/controllers/user/OrderManagement/orderController.js
- BACKEND/package-lock.json
- Frontend/src/Component/User/Login.jsx
- Frontend/src/Component/User/Registration.jsx
- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
- 🕰 **Add timezone according to area** to ensure correct timestamps in order history.  
- ⏳ **Add loader on Sign In & Sign Up buttons** to improve user feedback and responsiveness.  
- 💰 **Add price calculation based on cloth weight** for accurate billing and transparency.  
- 🌐 **Store frontend link in `.env` file** for better environment management and deployment flexibility.  
- ⏳ **Reduce password reset link expiration time from 5 minutes to 3 minutes** for enhanced security.  
- ✅ **Enhanced UI responsiveness** with loading indicators.  
- 🛠 **Better price calculation** for submitted orders.  
- 🔒 **Stronger security** by reducing password reset link validity.  
🚀 This update ensures **better accuracy, usability, and security** for the application! 🚀
> ✨ Improve User Experience & Timezone Adjustments

- Frontend/src/App.jsx
- Frontend/src/Component/User/Complaint-Form/ComplaintForm.jsx
- Frontend/src/Component/User/Complaint-Form/ComplaintFormSuccess.jsx
- 📝 **Integrated Complaint Form** using Web3Forms for email submission.  
- 🎉 **Added Success Page** to confirm form submission.  
- 🔄 **Imported Success Page** and linked it to the complaint form.  
- Implemented a **Web3Forms-powered complaint form** for seamless submissions.  
- Used **context to fetch bag number** dynamically.  
- Added **loading state** in the submit button (`Submitting...` with faded blue color).  
- Redirects to a **confirmation page** upon successful submission.  
1. Fill out the complaint form and click **Submit Complaint**.  
2. The button should show **Submitting...** in a faded blue color.  
3. Upon success, you should be redirected to the **success page**.  
🚀 Ready for review! Let me know if any improvements are needed.
> 🔧 Add Complaint Form with Web3Forms & ✅ Complaint Submission Success Page

- Frontend/package-lock.json
- Frontend/src/App.jsx
- Frontend/src/Component/Worker/Dashboard/workerDashbaord.jsx
- Frontend/src/Component/Worker/Navbar/Navbar.jsx
- Frontend/src/Component/Worker/workerDashbaord.jsx
This PR introduces the Worker Dashboard with the following enhancements:
- ✅ Implemented a **fixed Navbar** for seamless navigation.
- 🎨 Styled the Navbar with **active link highlighting** for better UX.
- 📱 Ensured **responsive design** for smooth experience across all devices.
- 🔀 Added necessary **routes** for the Worker Dashboard.
- Added Worker Navbar with **fixed positioning**.
- Applied **active link styling** to indicate the current section.
- Improved **layout and responsiveness** for better UI experience.
- Integrated new **route for the Worker Dashboard**.
> 🛠️ Implement Worker Dashboard with Fixed Navbar & Responsive Design 🚀

- BACKEND/controllers/worker/All-Orders/allorders.js
- BACKEND/routes/Worker/Get-All-Orders/allOrders.js
- BACKEND/server.js
This PR introduces several key enhancements for the worker dashboard, including order fetching, order summaries, and route setup. Below are the details of the changes:
---
- 🚀 Implemented `getWorkerOrders` function to fetch all orders for a worker's dashboard.
- 📊 Included total number of orders, pending orders, and completed orders in the response.
- 🔍 Populated user details for each order using the `populate` method.
- 📝 Formatted order information including bag number, user name, number of items, status, date, and time.
- 📌 Added route to get all order details for the worker dashboard.
- 🔄 Configured the route to handle worker account controls and order fetching.
---
✅ Workers can now view a comprehensive summary of orders on their dashboard.  
✅ Enhanced error handling for improved …
> 🎉 Enhance Worker Dashboard: Add Order Fetching, Summaries, and Route Setup 📝

- Frontend/src/Component/Worker/Dashboard/workerDashbaord.jsx
- Frontend/src/Component/Worker/OrdersManagement/OrderManagement.jsx
🌟 This PR brings the shiny new `OrderManagement` component and levels up the `WorkerDashboard` with juicy API-powered stats! 🎉 It’s all about showing off orders and crunching numbers like a pro. 💪
- 🌟 **Feature**: Added `OrderManagement` to show pending ⏳ and completed ✅ orders.
- 🔍 **Search**: Tossed in a search bar to hunt by bag number. 🕵️‍♂️
- 🎨 **UI**: Built slick, responsive tables with Tailwind CSS and Lucide icons. 🖼️
- 🌐 **API**: Grabs order goodies from `https://laundry-buddy-yysq.onrender.com/worker/getallorderdetails`. 📡
- ⏳ **Loading**: Added `LoaderM` to keep things smooth while fetching. 🌀
- 🌐 **API Magic**: Fetches total orders 📦, completed orders ✅, and pending orders ⏳ from the API. 🚀
- 📈 **Metrics**: Crunching the completion rate (`completedOrders / totalOrders * 100`) …
> ✨ Add OrderManagement & 🚀 Enhance WorkerDashboard with API Metrics 📊

- BACKEND/controllers/worker/All-Orders/allorders.js
- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
- Frontend/src/Component/Worker/Dashboard/workerDashbaord.jsx
- Frontend/src/Component/Worker/OrdersManagement/NotifyAndComplete.jsx
- Frontend/src/Component/Worker/OrdersManagement/OrderManagement.jsx
🌟 This PR adds the UI for the `NotifyAndComplete` modal to the `OrderManagement` component, enhancing the user interface. 🚀 Additionally, it updates the API response to include the `orderId` for improved tracking and debugging. 🛠️
- 🎨 Introduced the `NotifyAndComplete` modal UI with Tailwind CSS for a clean, mobile-responsive design.
- 👁️ Designed the modal to display order details, including `orderId` and customer name.
- ⏳ Included a placeholder for future functionality (e.g., status update and notification).
- 📱 Ensured responsiveness across desktop and mobile screens.
- 📡 Modified the backend API to return the `orderId` in the response for successful requests.
- 🔧 Updated the API response structure to support future status update logic.
1. **Modal UI**:
- 🏃‍♂️ Navigate to the Order …
> ✨ Add Notify & Update Modal & 📡 Include orderId in API Response 📊

- BACKEND/controllers/worker/All-Orders/allorders.js
- BACKEND/models/userOrder.js
- BACKEND/package-lock.json
- BACKEND/package.json
This PR introduces Twilio integration for sending SMS notifications when order statuses are updated. Additionally, a new `smsSent` field is added to the Order model for improved tracking of notification delivery.  
- 📞 Integrated Twilio for SMS notifications.  
- 🗄️ Added `smsSent` field to the Order model for tracking SMS status.  
- 🔧 Installed Twilio dependency.  
1. 🚀 Submit a new order.  
2. 📩 Verify that the registered phone number receives an SMS notification.  
3. 🔎 Confirm that the `smsSent` field is correctly updated in the database.  
- Ensure `.env` includes valid Twilio credentials.  
- Tested for both successful and failed SMS scenarios.
> 📲 Integrate Twilio SMS Notifications 🚀 | 📝 Added smsSent Field for Tracking

- BACKEND/package-lock.json
- BACKEND/package.json
- BACKEND/server.js
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
- Frontend/src/Component/Worker/OrdersManagement/OrderManagement.jsx
* Order details should be automatically fetched and displayed in the worker panel without needing to refresh the page.
* Workers see updates in real-time, making the process seamless and efficient.
> Fetch Order Details on Worker Panel without Page Refresh #61

- BACKEND/server.js
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/Component/User/SubmitOrder/Submitorder.jsx
- Frontend/src/Component/Worker/Dashboard/workerDashbaord.jsx
- Frontend/src/Component/Worker/OrdersManagement/NotifyAndComplete.jsx
- Frontend/src/Component/Worker/OrdersManagement/OrderManagement.jsx
This Pull Request resolves merge conflicts. The conflicts have been carefully reviewed and resolved to ensure accuracy and consistency.
- Resolved merge conflicts .
- Verified that the content is structured properly and adheres to the required format.
- The resolved conflicts ensure that the file is updated with the latest changes from both branches.
> Resolved Merge Conflicts

- BACKEND/controllers/worker/All-Orders/allorders.js
- Frontend/package-lock.json
- Frontend/src/Component/Worker/Dashboard/workerDashbaord.jsx
- Frontend/src/Component/Worker/OrdersManagement/NotifyAndComplete.jsx
This pull request addresses an issue where the frontend displayed an error message (`"Failed to update order status. Please try again."`) despite the backend successfully updating the order status and sending an SMS. The root cause was traced to a misinterpretation of the API response, and this PR fixes that while enhancing error handling and debugging capabilities.
- **Fixed False Error Display** ✅  
Corrected the logic in the `NotifyAndComplete` component to properly handle successful API responses, ensuring the modal closes without showing an error when the backend succeeds.
- **Enhanced Logging** 📜  
Added detailed `console.log` statements in `handleSubmit` to trace the request payload and API response, making it easier to debug future issues.
- **Improved Error Handling** 🛡️ …
> Fix Error in Updating Order Status and Improve Frontend Error Handling 🚀

- Frontend/src/Component/Worker/Dashboard/GenerateReport.jsx
- Frontend/src/Component/Worker/Dashboard/NewOrder.jsx
- Frontend/src/Component/Worker/Dashboard/workerDashbaord.jsx
This pull request introduces the functionality to pass order data (total, pending, completed) from the `WorkerDashboard` parent component to the `GenerateReport` child component and display the information in an interactive user interface.
- **WorkerDashboard**: Implemented logic to send total, pending, and completed order data to the `GenerateReport` component as props.
- **GenerateReport**: Displayed the passed order data in the report statistics section, along with an input for additional notes.
- Improved the communication flow between parent and child components to ensure a seamless data-sharing experience.
- Added user-friendly UI sections for viewing statistics and entering notes for better usability.
The updated `GenerateReport` component now visually presents:
- 📊 **Total …
> 🚀 Add order data passing and display functionality in GenerateReport component.
